all:
	gcc -o changeReadPolicy changeReadPolicy.c
	gcc -o getcnt counter_get.c
	gcc -o rstcnt counter_reset.c

changeReadPolicy:
	gcc -o changeReadPolicy changeReadPolicy.c

getcnt:
	gcc -o getcnt counter_get.c

rstcnt:
	gcc -o rstcnt counter_reset.c

clean:
	rm -rf changeReadPolicy getcnt rstcnt a.out
